stages:
 - check
 - test
 - build
 - docker


variables:
 MAVEN_CLI_OPTS: "-B -Dmaven.repo.local=.m2/repository"
 IMAGE_NAME: "nexus:8085/mr/spring-petclinic"


checkstyle:
 stage: check
 image: maven:3.9.9-openjdk-23
 script:
   - mvn checkstyle:checkstyle -Dcheckstyle.failOnViolation=false
 artifacts:
   paths:
     - target/checkstyle-result.xml
   when: always


unit_tests:
 stage: test
 image: maven:3.9.9-openjdk-23
 script:
   - mvn test


build_jar:
 stage: build
 image: maven:3.9.9-openjdk-23
 script:
   - mvn package -DskipTests


docker_build_mr:
 stage: docker
 image: docker:latest
 services:
   - docker:dind
 variables:
   DOCKER_HOST: "docker.io"
   IMAGE_NAME: spring-pet-clinic
   TAG_LATEST: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
 before_script:
   - apk add --no-cache python3 py3-pip
   - pip3 install --no-cache-dir awscli
 script:
   - aws ecr get-login-password --region $AWS_REGION |
      docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
   - docker build --cache-from $TAG_LATEST -t $TAG_LATEST .
   - docker push $TAG_LATEST


