version: '3.7'

services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    networks:
      - petclinic-net

  spring-petclinic:
    image: spring-petclinic-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    restart: always
    networks:
      - petclinic-net

networks:
  petclinic-net:
    driver: bridge
